### ISSUE TITLE
How configure the backend envirement and staring api server?

### ISSUE THREAD

**Issue by xins981** [justxuewei/libelula#20]
hello, predecessor. I want to run your project and study your implement idea. toward php, I know very little, if posibble, I wish recived your help about configure php development envirement and debug api that exposed frontend page.

**Comment by justxuewei** [comment]
Hi, I think this project's readme gives you very detailed steps about how to setup this project. If you are talking about how to setup PHP, I'd like to recommend you refer to [Laravel](https://laravel.com/) and [LAMP](https://en.wikipedia.org/wiki/LAMP_(software_bundle)). The `composer.json` tells this project's dependences which could be read by the [Composer](https://getcomposer.org/), a PHP dependence manager.

**Comment by xins981** [comment]
I understand, thanks!

**Comment by xins981** [comment]
学长，您的工作很扎实，向您认真的态度学习。
学弟苦于如何将 react + laravel 框架 部署到 UTACloud。老师给的ppt里介绍了部署静态页面，但是动态页面不知从何下手。作为前辈，我想您也有同样的经历，如果可以的话，请您指导一下思路。
抱歉周末打扰您，祝您和家人生活愉快！




On 4/3/2023 10:23，Xuewei ***@***.***> wrote：

Hi, I think this project's readme gives you very detailed steps about how to setup this project. If you are talking about how to setup PHP, I'd like to recommend you refer to Laravel and LAMP. The composer.json tells this project's dependences which could be read by the Composer, a PHP dependence manager.
